### ISSUE TITLE
AttributeError: 'module' object has no attribute 'PY34'

### ISSUE THREAD

**Issue by WantedFreak** [fake-name/xA-Scraper#320]
```
root@xa:~/xA-Scraper# python3 main.py
Sqlite database path: 'sqlite:////root/xA-Scraper/sqlite_db.db'
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    import xascraper.status_monitor
  File "/root/xA-Scraper/xascraper/__init__.py", line 74, in <module>
    from . import views
  File "/root/xA-Scraper/xascraper/views/__init__.py", line 2, in <module>
    from . import main_views
  File "/root/xA-Scraper/xascraper/views/main_views.py", line 28, in <module>
    import main
  File "/root/xA-Scraper/main.py", line 27, in <module>
    import xascraper.modules.da.daScrape as das
  File "/root/xA-Scraper/xascraper/modules/da/daScrape.py", line 10, in <module>
    import WebRequest
  File "/usr/local/lib/python3.4/dist-packages/WebRequest/__init__.py", line 2, in <module>
    from .WebRequestClass import WebGetRobust
  File "/usr/local/lib/python3.4/dist-packages/WebRequest/WebRequestClass.py", line 45, in <module>
    from . import ChromiumMixin
  File "/usr/local/lib/python3.4/dist-packages/WebRequest/ChromiumMixin.py", line 16, in <module>
    import ChromeController
  File "/usr/local/lib/python3.4/dist-packages/ChromeController/__init__.py", line 2, in <module>
    from .tab_pool import TabPooledChromium
  File "/usr/local/lib/python3.4/dist-packages/ChromeController/tab_pool.py", line 11, in <module>
    from ChromeController.manager import ChromeRemoteDebugInterface
  File "/usr/local/lib/python3.4/dist-packages/ChromeController/manager.py", line 27, in <module>
    ChromeRemoteDebugInterface_base = gen.get_class_def()
  File "/usr/local/lib/python3.4/dist-packages/ChromeController/Generator/gen.py", line 493, in get_class_def
    ret = instance.compile_class()
  File "/usr/local/lib/python3.4/dist-packages/ChromeController/Generator/gen.py", line 482, in compile_class
    exec(code)
  File "no filename", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/ChromeController/transport.py", line 18, in <module>
    import websocket
  File "/usr/local/lib/python3.4/dist-packages/websocket/__init__.py", line 23, in <module>
    from ._app import WebSocketApp
  File "/usr/local/lib/python3.4/dist-packages/websocket/_app.py", line 36, in <module>
    from ._core import WebSocket, getdefaulttimeout
  File "/usr/local/lib/python3.4/dist-packages/websocket/_core.py", line 34, in <module>
    from ._handshake import *
  File "/usr/local/lib/python3.4/dist-packages/websocket/_handshake.py", line 40, in <module>
    if six.PY34:
AttributeError: 'module' object has no attribute 'PY34'

root@xa:~/xA-Scraper# python3 --version
Python 3.4.3
```
Can't figure out what's causing this

**Comment by WantedFreak** [comment]
Running Ubuntu 14.04.2 LTS in a LXC container

**Comment by fake-name** [comment]
I'm.... not sure what's going on here.

The error is somewhere down in the [websocket](https://github.com/websocket-client/websocket-client) layer. 

https://github.com/websocket-client/websocket-client/issues/521 appears to be the same issue, but there was no resolution there either.

**Comment by WantedFreak** [comment]
> Is there a reason you're using such an old ubuntu? I generally use 16.04 or later. 14.04 is EoL in 3 months, and I haven't done anything on python 3.4 in a year or two now.

Its because that's what I had downloaded and ready to be deployed by Proxmox.
I will try Ubuntu 18.04 when I get home

**Comment by fake-name** [comment]
I don't *think* there is any reason it shouldn't work on 3.4.

Really, it sounds like some part of https://github.com/websocket-client/websocket-client has a metastable installation issue.
